name: coding
exp_name_postfix: local
experiment_description: Merge train+test+val for training, test for testing to check overfitting
random_seed: 47
dataset:
  name: atz
  voc_data: True
  data_root: ./data/THZ_dataset/THZ_dataset_det_VOC
  class_file: ./data/THZ_dataset/THZ_dataset_det_VOC/classes.txt
framework: pytorch
model:
  name: fasterrcnn_resnet50_fpn
  weights: None
train:
  flag: True
  batch_size: 6
  optimizer:
    name: Adam
  lr: 0.001
  lr_schedule_warmup_epoch: 1
  lr_schedule:
    flag: False
    name: LinearLR
    start_factor: 1
    total_iters: 2
  start_epoch: 1
  max_epoch: 50
  finetune:
    flag: True
    checkpoint_path: ''
  save_schedule: best # provide saving frequency, an integer, or best
  metrics: MeanAveragePrecision
inference:
  flag: False
  checkpoint_path: ''
