name: coding
experiment_description: Saving live progress. Early stopping. Model saving scheduler. Per model I/O signature for mlflow log_model()
exp_name_postfix: local
random_seed: 47
dataset:
  name: atz
  voc_data: True
  data_root: ./data/THZ_dataset/THZ_dataset_det_VOC
  class_file: ./data/THZ_dataset/THZ_dataset_det_VOC/classes.txt
framework: pytorch
model:
  name: fasterrcnn_resnet50_fpn
  weights: None
train:
  flag: True
  batch_size: 6
  optimizer:
    name: Adam
  lr: 0.001
  lr_schedule_warmup_epoch: 1
  lr_schedule:
    flag: False
    name: LinearLR
    start_factor: 1
    total_iters: 2
  start_epoch: 1
  max_epoch: 50
  finetune:
    flag: True
    checkpoint_path: ''
  save_schedule: # config when to save/log model
    type: metric # [epoch: epoch intervals, metric: highest performance, loss: lowest loss]
    key: test_map_75 # [if type=epoch, key=<integer>, if type=metric, key=<metric_name>, if type=loss, key=<loss_name>(in case we have multiple losses)]
    threshold: 0.6 # [minimum threshold after which the models should be considered for logging]
    value_delta: 0.02 # [an increase threshold of performance and a decrease loss to log the model]
  metrics: MeanAveragePrecision
inference:
  flag: False
  checkpoint_path: ''
